name: default
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pandas=0.23.2
  - gdal=2.4
  - matplotlib=3.1.0
  - pillow=6.0.0
  - seaborn=0.9
  - pytest=3.2.3
  - pytest-html=1.20.0
  - click=6.7
  - ipython
  - fiona=1.8.4
  - rasterio=1.0.23
  - rasterstats=0.13.0
  - geopandas=0.4.1
  - xlrd=1.1.0
  - descartes=1.1
  - xarray=0.12.1
  - netcdf4=1.5.1.2
  - pyyaml=5.1
  - pip=19.1.1
  - pycountry=19.8.18
  - pip:
      - pytest-pythonpath # adds the root path "./" to PYTHONPATH
